[toolchain]
package_manager = "pnpm"
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kzp_mini = "6kf3ieibPCviUiySokEPmfxXP3dB7bW4eb9aof7sdkX2"

[programs.devnet]
kzp_mini = "6kf3ieibPCviUiySokEPmfxXP3dB7bW4eb9aof7sdkX2"

[programs.mainnet]
kzp_mini = "6kf3ieibPCviUiySokEPmfxXP3dB7bW4eb9aof7sdkX2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo nextest --workspace"
deploy-localnet = "bash scripts/deploy.sh localnet"
deploy-devnet = "bash scripts/deploy.sh devnet"
deploy-mainnet = "bash scripts/deploy.sh mainnet"

[hooks]
