[workspace]
members = [
    "cli",
    "programs/*",
    "tests",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/vvylym/kzp-mini"

[workspace.dependencies]
anchor-lang = "1.1.2"
anchor-spl = "1.1.2"
kzp-mini = { path = "programs/kzp-mini" }
solana-client = "4.1.0"
solana-program-test = { version = "4.1.0", features = ["agave-unstable-api"] }
solana-sdk = "4.0.1"
tokio = { version = "1.52", features = ["macros", "rt-multi-thread"] }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
