[package]
name = "kzp-tests"
version = "0.1.0"
description = "KZP minimal integration tests"
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
kzp-mini.workspace = true
anchor-lang.workspace = true
anchor-spl.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
tokio.workspace = true
